// Fetching a single patient
export const FETCH_PATIENT_REQUEST = 'FETCH_PATIENT_REQUEST';
export const FETCH_PATIENT_SUCCESS = 'FETCH_PATIENT_SUCCESS';
export const FETCH_PATIENT_FAILURE = 'FETCH_PATIENT_FAILURE';

// Fetching list of patients
export const FETCH_PATIENTS_REQUEST = 'FETCH_PATIENTS_REQUEST';
export const FETCH_PATIENTS_SUCCESS = 'FETCH_PATIENTS_SUCCESS';
export const FETCH_PATIENTS_FAILURE = 'FETCH_PATIENTS_FAILURE';

// Fetching a single doctor
export const FETCH_DOCTOR_REQUEST = 'FETCH_DOCTOR_REQUEST';
export const FETCH_DOCTOR_SUCCESS = 'FETCH_DOCTOR_SUCCESS';
export const FETCH_DOCTOR_FAILURE = 'FETCH_DOCTOR_FAILURE';

// Fetching list of doctors
export const FETCH_DOCTORS_REQUEST = 'FETCH_DOCTORS_REQUEST';
export const FETCH_DOCTORS_SUCCESS = 'FETCH_DOCTORS_SUCCESS';
export const FETCH_DOCTORS_FAILURE = 'FETCH_DOCTORS_FAILURE';

// Fetching list of specialties
export const FETCH_SPECIALTIES_REQUEST = 'FETCH_SPECIALTIES_REQUEST';
export const FETCH_SPECIALTIES_SUCCESS = 'FETCH_SPECIALTIES_SUCCESS';
export const FETCH_SPECIALTIES_FAILURE = 'FETCH_SPECIALTIES_FAILURE';

// Fetching list of visits
export const FETCH_PATIENT_VISITS_REQUEST = 'FETCH_PATIENT_VISITS_REQUEST';
export const FETCH_PATIENT_VISITS_SUCCESS = 'FETCH_PATIENT_VISITS_SUCCESS';
export const FETCH_PATIENT_VISITS_FAILURE = 'FETCH_PATIENT_VISITS_FAILURE';

// Adding new patient
export const ADD_PATIENT_REQUEST = 'ADD_PATIENT_REQUEST';
export const ADD_PATIENT_SUCCESS = 'ADD_PATIENT_SUCCESS';
export const ADD_PATIENT_FAILURE = 'ADD_PATIENT_FAILURE';

// Updating patient
export const UPDATE_PATIENT_REQUEST = 'UPDATE_PATIENT_REQUEST';
export const UPDATE_PATIENT_SUCCESS = 'UPDATE_PATIENT_SUCCESS';
export const UPDATE_PATIENT_FAILURE = 'UPDATE_PATIENT_FAILURE';

// Adding new doctor
export const ADD_DOCTOR_REQUEST = 'ADD_DOCTOR_REQUEST';
export const ADD_DOCTOR_SUCCESS = 'ADD_DOCTOR_SUCCESS';
export const ADD_DOCTOR_FAILURE = 'ADD_DOCTOR_FAILURE';

// Updating doctor
export const UPDATE_DOCTOR_REQUEST = 'UPDATE_DOCTOR_REQUEST';
export const UPDATE_DOCTOR_SUCCESS = 'UPDATE_DOCTOR_SUCCESS';
export const UPDATE_DOCTOR_FAILURE = 'UPDATE_DOCTOR_FAILURE';

// Adding new visit
export const ADD_VISIT_REQUEST = 'ADD_VISIT_REQUEST';
export const ADD_VISIT_SUCCESS = 'ADD_VISIT_SUCCESS';
export const ADD_VISIT_FAILURE = 'ADD_VISIT_FAILURE';

// Updating visit
export const UPDATE_VISIT_REQUEST = 'UPDATE_VISIT_REQUEST';
export const UPDATE_VISIT_SUCCESS = 'UPDATE_VISIT_SUCCESS';
export const UPDATE_VISIT_FAILURE = 'UPDATE_VISIT_FAILURE';

// Log in user
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// Log out user
export const LOGOUT = 'LOGOUT';

// Clear alert
export const CLEAR_ALERT = 'CLEAR_ALERT';